### PR TITLE
Use NPM dependency instead of GIT

### PR DESCRIPTION
**Pull request by anxolin**
Apparently the PR #30 that uses a forked version of a Prometheus middleware failed when merged to master although it had a green light in the PR branch.
* Master: https://travis-ci.org/github/gnosis/dex-price-estimator/builds/680479475
* branch. https://travis-ci.org/github/gnosis/dex-price-estimator/builds/680472365

I think the difference is that in master it tries to build the docker image.
It looks like yarn had trouble resolving the forked dependency using GIT.

I've made a NPM package while the original project don't merge my PR. It's been sitting there for 8 days. This PR justs adds this NPM package

NOTE: The change it shows in `src/index.ts` it's the auto formatter kicking in

### CODE REVIEW

**Review by josojo — COMMENTED** [review]
LGTM, thanks for fixing the issue so quickly

**Review by josojo — APPROVED** [review]

**Review by fleupold — APPROVED** [review]
Thanks for fixing. As a hint, you can save without auto-formatting using `cmd+k, s` in VSCode. 

Eventually we should probably just have a PR that enforces formatting as a lint step and applies this to the entire codebase.

**Comment by anxolin** [comment]
> Eventually we should probably just have a PR that enforces formatting as a lint step and applies this to the entire codebase.

We use husky for that. Very simple tool

**Comment by fleupold** [comment]
> We use husky for that. Very simple tool

I believe husky does pre-commit hooks which are optional (I can `git commit --no-verify`). I'd prefer a simple format check as part of our travis pipeline.

**Comment by anxolin** [comment]
It make sense to have both. I think we have them for our projects:
husky --> check before commit
travis --> check that some formatting issue didn't make it to the remote. Thanks to ☝️, it shouldn't happen

**Pull request merged**
