### PR TITLE
Rename price endpoint to buy amount

### PR DESCRIPTION
**Pull request by fleupold**
Based on the discussion in https://github.com/gnosis/dex-react/issues/790 it seems like a price endpoint should be taking decimal places into account.

I strongly believe there is a use case for estimating just the projected buyAmount (without doing any decimal adjustments), thus this PR is moving the current price estimation logic to a separate endpoint, which will allow re-adding a price endpoint that adjusts for decimals.

### Test Plan

e2e tests + making sure 

http://localhost:8080/buy-amount?sellToken=4&buyToken=1&sellAmount=1000000

and

http://localhost:8080/buy-amount?sellToken=1&buyToken=4&sellAmount=1000000000000000000

return reasonable buy amounts.

### CODE REVIEW

**Review by bh2smith — APPROVED** [review]

**Review by nlordell — APPROVED** [review]

**Comment by anxolin** [comment]
It took me a bit to understand what this endpoint would return. 

I think it's very useful if I understand correctly, just not super convinced on the name or the fact it doesn't use decimals.

Regarding the name. I understand this returns the expected amount of the recing token that you would probably get if you place an order of the given sell amount.
The confusing i had initially when I saw it first, is than in `REST` semantics, `GET /buy-amount` would look like I'm getting the buy amount (total tokens being buyed or sth). 

Normally the endpoints follow a hierarchy, like:
* `/markets`
* `/markets/weth-dai`
* `/prices`
* `/prices/weth-dai`
* `/prices/weth-dai/expected-receive-amount`
* "sellToken=4&buyToken=1&sellAmount=1000000" are params, ideally for a REST design they should be optional. One way to achieve this is to have a default sellAmount (1 unit, not in weis), and then make the tokens part of the resource

My proposal for you endpoint would allow to query this URLs:
`/prices/4-1/expected-receive-amount`
`/prices/4-1/expected-receive-amount?sellAmount=0.1`
`/prices/WETH-DAI/expected-receive-amount`
`/prices/0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2-0x89d24a6b4ccb1b6faa2625fe562bdd9a23260359/expected-receive-amount`

Last 2 endpoints, as a nice to have, probably for the future.

**Comment by fleupold** [comment]
@anxolin  Agree the name is not very clear. Technically it's also not the expectedReceiveAmount but more the "receivable" amount (the amount you can place an order for that is expected to get matched).

My problem with `/prices/4-1/expected-receive-amount?sellAmount=0.1` is that it doesn't really imply what currency is being bought and sold (you have to start wrapping you head around base and quote tokens again).

Also, while /prices/WETH-DAI looks nice, is it good practice to allow different types in the hierarchy (e.g. mix tokenIDs or Symbols and contract address on the path position)?

One more thing to note is that sellAmount is not optional. It doesn't make sense to quote a price without an amount (there are remaining dust orders at really unreasonable prices), so you might be able to buy 0.001 DAI very cheaply. If we want to define a "default amount" this would likely again have to depend on the decimals **and** price (e.g. 1 DAI is much less than 1BTC).

Overall I think we should be careful of bike-shedding this API too much.

Maybe it makes more sense to look at the overall URL, which at the moment would be

https://price-estimate-mainnet.dev.gnosisdev.com/buy-amount?sellToken=1&buyToken=4&sellAmount=1000000000000000000

But if you feel strongly I can change it to be

https://price-estimate-mainnet.dev.gnosisdev.com/prices/1-4/buyAmount?sellAmount=1000000000000000000

Let me know.

**Comment by anxolin** [comment]
>  Technically it's also not the expectedReceiveAmount but more the "receivable" amount (the amount you can place an order for that is expected to get matched).

Ok

> My problem with /prices/4-1/expected-receive-amount?sellAmount=0.1 is that it doesn't really imply what currency is being bought and sold (you have to start wrapping you head around base and quote tokens again).

I agree `/prices/4-1/expected-receive-amount` can sound sound a bit strange. 4-1 identify the market. So technically is not that bad. 
It's simple to see how `/tweets` it's a list of tweets, and `/tweets/123` is a tweet identified by 123. Here would be something similar, we are targeting from all the prices, one identified by that specific market, and from the price, we are interested in the amount of tokens that are receivable


> One more thing to note is that sellAmount is not optional. It doesn't make sense to quote a price without an amount (there are remaining dust orders at really unreasonable prices), so you might be able to buy 0.001 DAI very cheaply. If we want to define a "default amount" this would likely again have to depend on the decimals and price (e.g. 1 DAI is much less than 1BTC).

100% agree. I just don't like to much query params that are not optional, and I don't like a decimal amount as part of the name of the rest resource. This is why, I thought it was not that bad to have a default. Users can still provide the parameter, normally they would do.

With the analogy of the `/tweets`, `/tweets` would return already some defaults, but normally people would want to add some tags for example `/tweets?tag=codvid`

> Overall I think we should be careful of bike-shedding this API too much.

Agree too. I just offered the thoughts I had while reviewing. It's very likely that we will have more endpoints in the future, and having this conversations set's a common ground and they are beneficial. If designed right, you won't need to tell the people using the API they need to change their bots and apps so often.
I don't want to overthink it, my comments I think are just some typical good practices in Rest API designs, however is not the end of the world to not follow all of this. Many exchanges have super unorthodox API and people use them anyways.

If you really like the original route, and want to use weis, go for it.

**Comment by fleupold** [comment]
> If you really like the original route, and want to use weis, go for it.

I do feel strongly about offering an API that gives you the amount in the same unit that you will need if you want to place an order on the contract (I will add another one returning human readable prices/amounts on top of that).

I don't feel strongly about the route name, but am still not fully certain about the semantics:

Would `/prices/4-1/expected-receive-amount` assume I'm trying to sell token 4 and receive token 1 or vice versa?

**Comment by bh2smith** [comment]
> Overall I think we should be careful of bike-shedding this API too much.

Today I learned a new term!

**Comment by anxolin** [comment]
> Would /prices/4-1/expected-receive-amount assume I'm trying to sell token 4 and receive token 1 or vice versa?

I think market "4-1" would be same as saying "USDC-WETH" or even "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48-0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2" and would mean:
* I'm buying USDC
* I'm paying in WETH
* The price is the number of WETH you need to pay for every unit of USDC

**Review by anxolin — APPROVED** [review]
I still believe that the API I'm proposing is more a standard REST API design:
* using versioning in the route
* using a hierarchy of resources
* relying less in query params: ideally no mandatory query params
* trying to be as close as possible to user friendliness (units instead of weis). For checking the values, monitoring, read only apps, we'll move the responsibility of knowing the precision of the tokens to the clients. At least efrontier complained about this when they worked in the graph. Reason why we abstracted this away.

I also understand your argument on using weis if the smart contract is what it gets. It's a fair point, for me has less importance than facilitating the reading of this information, because who sends a transaction technically will have more logic in place than someone that is just checking the prices or playing with the API.

In any case, I want to approve, cause this discussions becomes a bit nitpick and I like the overall new service and API and I'm ok using weis or that other naming as a first version and reiterate based on feedback. I don't want to slow down this great PRs from seeing the light :)

**Comment by nlordell** [comment]
Just my two cents:
From what I understand from REST, is that you attempt to represent endpoints as resources, using paths as a way to show hierarchy within the resource. With that in mind, I think defining a market as a resource makes a ton of sense:
- `/markets/USDC-WETH`

So, now for the first endpoint, for retrieving the orderbook, it makes perfect sense for it to be a sub-resource of our market resource, as an orderbook is (at least how I see it) a property of a market:
- `/markets/USDC-WETH/orderbook` to retrieve the orderbook between USDC and WETH
- `/markets/USDC-WETH/orderbook?maxHops=3` to specify an optional max number of hops value to the orderbook calculation.

That being said, I tend to agree with @fleupold that `/prices/4-1/expected-receive-amount` is pretty ambiguous and is kind of unclear what is the endpoint actually represents: is it how much of token 1 I receive for some amount of token 4 or how much token 4 I receive for some amount of token 1? What is the amount we are talking about WRT slippage? While I can make a guess to the first question, it will definitely be a guess that feels 50-50 and without checking some docs or trying it out I can't really be confident in my guess.

**Comment by nlordell** [comment]
Just my two cents:
From what I understand from REST, is that you attempt to represent endpoints as resources, using paths as a way to show hierarchy within the resource. With that in mind, I think defining a market as a resource makes a ton of sense:
- `/markets/USDC-WETH`

So, now for the first endpoint, for retrieving the orderbook, it makes perfect sense for it to be a sub-resource of our market resource, as an orderbook is (at least how I see it) a property of a market:
- `/markets/USDC-WETH/orderbook` to retrieve the orderbook between USDC and WETH
- `/markets/USDC-WETH/orderbook?maxHops=3` to specify an optional max number of hops value to the orderbook calculation.

That being said, I tend to agree with @fleupold that `/prices/4-1/expected-receive-amount` is pretty ambiguous and is kind of unclear what is the endpoint actually represents: is it how much of token 1 I receive for some amount of token 4 or how much token 4 I receive for some amount of token 1? What is the amount we are talking about WRT slippage? While I can make a guess to the first question, I can't really know the answer to the second one.

Some other suggestions off the top of my head: 
- `/markets/USDC-WETH/price/10000000USDC`

**Comment by nlordell** [comment]
However, now that I think about it a little more, it seems that the price in a `USDC-WETH` market seems to be pretty well defined as the price in `WETH` of `USDC` (see [Kraken prices](https://trade.kraken.com/markets) for example).

With that in mind, `/markets/USDC-WETH/price` or `/prices/USDC-WETH/expected-buy-amount` make a lot more sense, but this does hide the importance of the amount for the price. For me a price without an amount is the middle of the spread.

**Comment by anxolin** [comment]
Thanks @nlordell , yes defining hierarchy of resources make sense, it make it intuitive to know how is the "list all of markets endpoint" (`/markets`) or how you refer to one in particular (`/markets/USDC-WETH`) or how to get some subentity of it as you suggest with the price `/markets/USDC-WETH/price`

nitpick:  In URLs is better to use kebab case, so it would be `/markets/USDC-WETH/orderbook?max-hops=3` or `/markets/USDC-WETH/orderbook?hops=3`

Regarding the endpoint you proposed for the order book, I was going to suggest it also, but I dropped the `/orderbook` part because It made sense to me that `/markets/USDC-WETH` would return that and it was simpler. But on a second view, it's possibly better to be more explicit, you might want the book, or tickers, or anything you want to refer from the market.

From your suggestion `/markets/USDC-WETH/price/10000000USDC`
* I like the `/markets/USDC-WETH/price/10000000` part
* I'm not excited with the 10000000USDC part

Although I like `/markets/USDC-WETH/price` the reason I suggested `/prices/USDC-WETH` it's because I thought the resource would have enough importance/entity and would give us simpler URLs, however I like the other one too, and I like to build this hierarchy consistently

------

@fleupold and I were also chatting about this to avoid spamming more this thread, we agreed that the units that can be a bit difficult to see.
Some ideas that poped proposed in our chat:

If you go to the market to buy Lemons, you check the offer (asks) and get a quote:
* `/markets/Lemons-Dollar/asks/estimated-volume-for-quote/1000`
* Meaning: From all the people selling, tell me the Lemons I get if I pay 1000$

If you are a Lemon Merchant:
* `/markets/Lemons-Dollar/bids/estimated-volume-for-base/50`
* From all the people bidding, how many dollars do I get for 50 Lemons

Felix was not super excited with adding asks/bids, he is probably right and something like this is more suitable:
* `/markets/Lemon-Dollar/estimated-volume-for-selling-quote`
* `/markets/Lemon-Dollar/estimated-volume-for-buying-base`

---- 

Last thought about amounts. The example of exchanges I checked, they use units (Bitfinex, Kyber, Dex.ag) so I do feel is better to work with units than wei. It can get messy for users for tokens with different decimals. If someone send a tx to the smart contract, I understand that person can easily convert to weis, rather than making casual consumers of the API for amounts/price convert from weis to units.

**Comment by anxolin** [comment]
Some more food for thought, sorry if it's too much bike-shedding, whatever first release of the endpoints it's going to be great, and we can reiterate, so no need to wait for this conversation to be 100% settled, but it's important to have at least an early conversation about the API.

So we didn't talk about the return type. I saw some exchanges to make it more explicit they return a structure with the `quoteAmount` `baseAmount`, `quoteCurrency`, `baseCurrency`. That'd be nice, and we could release some responsibility from the name of the endpoint :)

From the current proposal compared to the original ones, I like that they have less parameters. It's clear what is mandatory and optional. On top of that less parameters means more hits on both internal caches, and HTTP caches (http servers, CDN, etc) so we can catch for a few seconds, or a fraction of a second, or whatever that make sense ---> more scalable if people ask for round numbers that it's usually the case

**Comment by fleupold** [comment]
I like the idea of making the returned tokenID explicit by returning an object. The URLs proposed now are:

 - `/api/v1/markets/1-7/` to get the WETH-DAI orderbook (bids/ask)
- `/api/v1/markets/1-7/estimated-buy-amount/1000000000000000000` to get the amount of WETH we can expect to get when selling 1 DAI. It returns a dictionary like:

```
{"buyToken":"1","estimatedBuyAmount":7032275158038859}
```

I guess the question around decimals still remains (and is not clear from the name). I would like to offer an endpoint that returns base units / atoms (leaving the option to add an endpoint that takes decimals into account).

Maybe we should call it `estimated-base-unit-buy-amount` or even prefix the api with base-unit ?

**Comment by anxolin** [comment]
I like the proposal, I would add the following nitpicks:

for the returned object: `buyTokenId` instead of `buyToken`, or even we can use quote/base semantics

You don't like to add also the sell amount and token? Kyber do it, and I think it's more clear https://developer.kyber.network/docs/Trading/#buy-rate

> I guess the question around decimals still remains (and is not clear from the name). I would like to offer an endpoint that returns base units / atoms (leaving the option to add an endpoint that takes decimals into account).

I would use the same endpoint. Use units by default, allow to use atoms by using a parameter. Similar as how the exchanges show tickers for 10m, 1h, 2h and allow to change that by parameter but one is the default

**Comment by fleupold** [comment]
👍 on returning the sellAmount/token as well.

I'm ok with making the unit type optional on the same endpoint. However, this PR can only implement base quantity amounts (this is how the [DAI doc](https://docs.makerdao.com/smart-contract-modules/dai-module/dai-detailed-documentation#units) calls the "atoms").

For the human readable units we need more dependencies and the feature to read token data from chain which is more slightly more involved. I can make the "default" unimplemented for now although that seems slightly weird.

**Comment by anxolin** [comment]
I think Maker contracts called it "wad" but they are famous for having intelligible smart contract var names. I'm Ok with "wad" if people understand that. I have to admit I've been abusing the language all the time and calling them weis (I've seen I'm not the only one, so I kept doing it). Maybe that's a fun question for Martin, what's the name of the atoms :) 

Yes agree on your proposal, also, agree is weird that the default won't work, but I think it's fine. I'm sure we'll provide something easy to plug here and we will be able to accept: token addresses, symbols (with no risk of malicious tokens) and the units.

So all gooooood! 

<a href="https://gitme.me/image?url=https%3A%2F%2Fmedia3.giphy.com%2Fmedia%2F12VL9VvZ3ErqiQ%2Fgiphy.gif&token=surf" data-gitmeme-token="surf"></a>

**Comment by fleupold** [comment]
I was referring to the term "base quantity" or "base unit", since one could also consider 1 DAI as the base unit (but it looks like the literature calls the smallest unit "base_unit").

**Pull request merged**
