### PR TITLE
Sort orderbook by serialized price

### PR DESCRIPTION
**Pull request by fleupold**
The backend is supposed to return offers sorted (bids descending, asks ascending). 

The orderbook's `toJSON` method sorts its elements by `price`. Price is of type Fraction, which implements it's own `lt`/`gt` methods comparing numerator/denominator in BN representation (cf. https://github.com/gnosis/dex-contracts/blob/24e4a23429ae883a3dc6eb9956a407896cd5418a/src/fraction.ts#L18-L26).

However, the serialized json returns the price as a number and ordering in BN format is not necessarily preserved when rounding to numbers. E.g.:

```js
const smaller = new Fraction(
        new BN("2cd42711c557ec02d09d6f7e0e0", "hex"),
        new BN("2c8f7d89a459955fcc182dc00e3", "hex")
); // 1.0060190481092344

const larger = new Fraction(
        new BN("190ccccccccccccccccccccccccccd9bf0", "hex"),
        new BN("18e66e96b6904a657edfd9efcafe985789", "hex")
); // 1.0060190481092346

assert.isTrue(smaller.toNumber() < larger.toNumber());
assert.isTrue(smaller.lt(larger)); // This fails
```

This PR therefore add serialized ordering based on `toNumber()` to the backend code before sending the result out as JSON.

### Test Plan

Query `http://localhost:8080/api/v1/markets/4-2?atoms=true` and make sure the asks (particularly t price 1.0060190481092344 and 1.0060190481092346 are sorted in order).

### CODE REVIEW

**Review by josojo — APPROVED** [review]
code looks good and testplan works.

I have the suspicion that your ordering by BN is more accurate that your ordering by decimals. Probably, the error happens in the rounding from fraction to decimal and that is why you see the different results. 

Anyways, it makes perfect sense to sort by decimals, as this is what the users will see.

**Review by alfetopito — APPROVED** [review]

**Comment by anxolin** [comment]
I'm a bit lost, it looks like the same logic as the Orderbook `toJson` why duplicate it?

The part where I'm lost is, why there's a "rounding" here if we deal with fractions using big numbers?
A big number should never be converted to number, only to string it needs to be serialized. 

Am I missing sth?

**Comment by fleupold** [comment]
The orderbook `toJson` returns an object where the price is of type Fraction (with numerator and denominator) and it is correctly ordered by this type. However, when a fraction is actually written to JSON it is converted into a number (otherwise our price would have a numerator and denominator which would arguably make it harder to understand). This conversion doesn't preserve the original ordering (cf. the mentioned test case) and thus we need to reorder.

**Comment by alfetopito** [comment]
> The orderbook `toJson` returns an object where the price is of type Fraction (with numerator and denominator) and it is correctly ordered by this type. However, when a fraction is actually written to JSON it is converted into a number (otherwise our price would have a numerator and denominator which would arguably make it harder to understand). This conversion doesn't preserve the original ordering (cf. the mentioned test case) and thus we need to reorder.

What about returning the price as a string? You could cap at an arbitrarily higher precision and convert it to BN/BigNumber when consuming it.

**Comment by fleupold** [comment]
I think we could also cap numbers at an arbitrary precision, the question is which one (should probably depend on decimals and volume, so it wouldn't be the same across orderbooks). And then we would either have to re-aggregate the ticks instead of resorting.

**Comment by bh2smith** [comment]
I really like the example you provided... Did this come up somewhere or were you really converting approximately equal decimals into fractions with large `p` and `q` then converting to hex?

**Comment by fleupold** [comment]
@alfetopito discovered it while playing with the orderbook visualization on rinkeby.

**Pull request merged**
